In [552]:
import pandas as pd
from sqlalchemy import create_engine
import mysql.connector
import numpy as np

#set inf to 
numericslist = ['level_0','index','IndustryId','2005','2006','2007','2008','2009','2010','Dollar_Growth','Percentage_Growth']

### Store CSV into DataFrame

In [553]:
#define first source of data
csv_file = "Resources/GDP_Huge_Master2.csv"
#convert to df
metroGDPdata_df = pd.read_csv(csv_file, encoding='utf-8')
#replace non-numeric values with 0
metroGDPdata_df = metroGDPdata_df.replace(to_replace={'(D)': 0, '(L)': 0, '(NaN)':0})
metroGDPdata_df.fillna(value=0.0)

C:\Users\micha\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,2,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,GeoFIPS,GeoName,Region,ComponentId,ComponentName,IndustryId,IndustryClassification,Sector,Description,2001,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,1,â€¦,0.0,All industry total,9549104,...,13054952,13229897,12956728,13418482,13882335,14481568,14963370,15621759,16280446,16802781
1,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,2,...,0.0,Private industries,8379519,...,11450487,11552249,11229026,11633016,12073380,12649538,13108020,13717912,14317489,14793461
2,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,3,11,1.0,"Agriculture, forestry, fishing, and hunting",53672,...,74544,75104,70163,80025,93065,88881,103573,96985,85660,78223
3,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,4,111-112,0.0,Farms,40038,...,56385,57076,52252,60446,73107,66725,81026,73202,60724,(NA)
4,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,5,113-115,0.0,"Forestry, fishing, and related activities",13634,...,18160,18027,17911,19579,19959,22157,22547,23783,24935,(NA)
5,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,6,21,1.0,"Mining, quarrying, and oil and gas extraction",93497,...,237231,304781,210566,236802,286115,298500,334897,359348,239208,193145
6,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,7,211,0.0,Oil and gas extraction,66065,...,174506,236921,154274,173088,209027,222644,260842,280061,171100,(NA)
7,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,8,212,0.0,Mining (except oil and gas),13059,...,28077,28450,29081,34092,39330,35951,33547,33700,31609,(NA)
8,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,9,213,0.0,Support activities for mining,14373,...,34648,39411,27211,29623,37759,39905,40507,45587,36499,(NA)
9,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,10,22,0.0,Utilities,156016,...,198786,200584,210494,223712,228347,219818,224435,236355,237635,240544
10,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,11,23,0.0,Construction,437294,...,643461,583849,510591,475022,478403,511779,548503,596799,654176,704057
11,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,12,31-33,0.0,Manufacturing,1265802,...,1598622,1567676,1495032,1584914,1648251,1708514,1749181,1799750,1858773,1862575
12,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,13,"321,327-339",0.0,Durable goods manufacturing,722323,...,892026,863824,769540,837021,875444,915814,942878,977671,1017619,1025813
13,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,14,321,0.0,Wood product manufacturing,15438,...,16572,14239,11607,12015,12038,12749,14480,16011,16734,(NA)
14,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,15,327,0.0,Nonmetallic mineral product manufacturing,33398,...,41249,35245,29625,28641,28302,30373,34287,36223,38074,(NA)
15,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,16,331,0.0,Primary metal manufacturing,32478,...,51198,53955,32709,39192,46677,47968,45539,46731,44480,(NA)
16,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,17,332,0.0,Fabricated metal product manufacturing,93988,...,113721,111788,99644,101501,107303,116728,119336,123343,125704,(NA)
17,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,18,333,0.0,Machinery manufacturing,88726,...,107650,107344,96135,100710,113324,117740,120552,124955,125511,(NA)
18,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,19,334,0.0,Computer and electronic product manufacturing,168091,...,221230,228291,223408,243187,243415,250983,255122,260067,271811,(NA)
19,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,20,335,0.0,"Electrical equipment, appliance, and compo...",36192,...,40856,45335,41750,42036,40027,43087,46204,46955,47632,(NA)
20,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,21,3361-3363,0.0,"Motor vehicles, bodies and trailers, and p...",107203,...,103958,75358,40383,75337,89546,100933,107142,114893,130082,(NA)
21,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,22,3364-3369,0.0,Other transportation equipment manufacturing,72753,...,107286,104840,106205,106074,109056,107713,112033,118410,123066,(NA)
22,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,23,337,0.0,Furniture and related product manufacturing,23920,...,24770,21085,17320,16594,16827,17264,18899,19615,21112,(NA)
23,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,24,339,0.0,Miscellaneous manufacturing,50137,...,63536,66343,70753,71732,68928,70275,69284,70468,73413,(NA)
24,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,25,"311-316,322-326",0.0,Nondurable goods manufacturing,543479,...,706596,703852,725492,747893,772807,792700,806304,822079,841154,836762
25,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,26,311-312,0.0,Food and beverage and tobacco products man...,138490,...,150933,156110,188670,178008,167159,177378,182700,189804,198210,(NA)
26,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,27,313-314,0.0,Textile mills and textile product mills,18325,...,14172,13122,11212,11381,11019,11821,12326,13426,13589,(NA)
27,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,28,315-316,0.0,"Apparel, leather, and allied product manuf...",15686,...,9875,9713,8408,8964,8882,8693,8898,8734,8617,(NA)
28,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,29,322,0.0,Paper manufacturing,41186,...,42417,38848,44769,41992,39977,38909,42241,42716,45194,(NA)
29,998,United States (Metropolitan Portion),0,200,Gross domestic product (GDP) by metropolitan a...,30,323,0.0,Printing and related support activities,38921,...,43338,40607,35356,34902,34052,33774,34284,33718,34817,(NA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99945,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,65,56,0.0,Administrative and support and waste manage...,64,...,189,224,223,219,120,136,151,174,182,186
99946,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,66,561,0.0,Administrative and support services,59,...,176,212,211,207,109,123,137,158,165,(NA)
99947,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,67,562,0.0,Waste management and remediation services,6,...,13,12,11,12,10,12,14,15,16,(NA)
99948,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,68,"61, 62",0.0,"Educational services, health care, and socia...",289,...,391,431,439,444,454,463,455,447,453,460
99949,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,69,61,0.0,Educational services,5,...,17,16,16,15,16,16,15,16,16,16
99950,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,70,62,0.0,Health care and social assistance,283,...,375,415,423,429,438,447,440,431,437,444
99951,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,71,621,0.0,Ambulatory health care services,134,...,174,198,205,210,222,226,227,210,211,(NA)
99952,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,72,622-623,0.0,"Hospitals, nursing, and residential care f...",0,...,168,180,182,181,183,0,0,0,198,(NA)
99953,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,73,624,0.0,Social assistance,0,...,33,37,37,37,34,0,0,0,29,(NA)
99954,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,74,"71, 72",0.0,"Arts, entertainment, recreation, accommodati...",148,...,178,178,163,167,176,179,182,162,163,164
99955,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,75,71,0.0,"Arts, entertainment, and recreation",9,...,8,7,8,8,9,16,11,10,10,10
99956,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,76,711-712,0.0,"Performing arts, spectator sports, museums...",2,...,1,1,1,1,1,1,1,1,2,(NA)
99957,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,77,713,0.0,"Amusement, gambling, and recreation indust...",7,...,7,6,7,7,8,16,11,9,9,(NA)
99958,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,78,72,0.0,Accommodation and food services,139,...,170,172,155,159,167,163,170,152,153,154
99959,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,79,721,0.0,Accommodation,41,...,39,42,43,42,44,44,55,32,30,(NA)
99960,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,80,722,0.0,Food services and drinking places,97,...,132,129,112,117,123,118,115,120,123,(NA)
99961,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,81,81,0.0,Other services (except government and govern...,100,...,121,118,112,107,101,99,95,96,96,97
99962,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,82,...,0.0,Government and government enterprises,1234,...,1440,1547,1588,1627,1674,1688,1641,1598,1604,1609
99963,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,83,...,0.0,Federal civilian,275,...,377,405,426,428,436,438,416,408,413,(NA)
99964,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,84,...,0.0,Military,398,...,388,442,517,554,568,566,550,540,550,(NA)
99965,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,85,...,0.0,State and local,565,...,679,701,645,646,670,684,675,651,641,(NA)
99966,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,86,"11, 21",0.0,Natural resources and mining,601,...,825,657,665,876,915,621,839,717,960,1033
99967,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,87,"42, 44-45",0.0,Trade,452,...,696,686,631,639,610,630,645,658,665,702
99968,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,88,...,0.0,Transportation and utilities,113,...,196,192,175,193,213,190,186,207,204,194
99969,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,89,...,0.0,Private goods-producing industries,1038,...,1538,1232,1173,1294,1326,977,1168,1051,1350,1437
99970,49740,"Yuma, AZ (Metropolitan Statistical Area)",0,900,Real GDP by metropolitan area (millions of cha...,90,...,0.0,Private services-providing industries,1972,...,2482,2530,2447,2479,2477,2515,2549,2556,2567,2619
99971,Note: See the included footnote file.,0,0,0,0,0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
99972,"Last updated: September 20, 2017 -- new statis...",0,0,0,0,0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
99973,Source: U.S. Department of Commerce / Bureau o...,0,0,0,0,0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
99974,,0,0,0,0,0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Create new data with select columns

In [554]:
edited_metroGDPdata_df = metroGDPdata_df[['GeoName','IndustryId','Description','2005','2006','2007','2008','2009','2010']].copy()

edited_metroGDPdata_df.head()

,GeoName,IndustryId,Description,2005,2006,2007,2008,2009,2010
0,United States (Metropolitan Portion),1,All industry total,11790834,12485329,13054952,13229897,12956728,13418482
1,United States (Metropolitan Portion),2,Private industries,10339935,10963791,11450487,11552249,11229026,11633016
2,United States (Metropolitan Portion),3,"Agriculture, forestry, fishing, and hunting",67155,69507,74544,75104,70163,80025
3,United States (Metropolitan Portion),4,Farms,52251,51217,56385,57076,52252,60446
4,United States (Metropolitan Portion),5,"Forestry, fishing, and related activities",14904,18289,18160,18027,17911,19579

In [599]:
#Looked at the govt census bureau documentation, figured out that the govt. breaks down the economy into 3 major sectors, GO TO ACS PPTs

metroGDPdatabysector_df = edited_metroGDPdata_df.loc[edited_metroGDPdata_df['IndustryId'].isin(['82','89','90'])]
# metroGDPdatabysector_df = metroGDPdatabysector_df.groupby('GeoName').filter(lambda x : len(x)==3)
# metroGDPdatabysector_df.groupby('GeoName')
#Calculated GDP Change by cols (3 sectors separated already)
metroGDPdatabysector_df['Dollar_Growth'] = metroGDPdatabysector_df['2010'].astype('f4') - metroGDPdatabysector_df['2005'].astype('f4')
metroGDPdatabysector_df['Percentage_Growth']  = (metroGDPdatabysector_df['Dollar_Growth'].astype('f4') / metroGDPdatabysector_df['2005'].astype('f4') * 100)
#reset index in preparation for SQL
metroGDPdatabysector_df1 = metroGDPdatabysector_df
metroGDPdatabysector_df1.reset_index(drop=False,inplace=True)
metroGDPdatabysector_df1.reset_index(drop=False,inplace=True)
metroGDPdatabysector_df1.head()
# LEFT EXTRA INDEX THERE IN C

C:\Users\micha\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\micha\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,level_0,index,GeoName,IndustryId,Description,2005,2006,2007,2008,2009,2010,Dollar_Growth,Percentage_Growth
0,0,32790,"Winston-Salem, NC (Metropolitan Statistical Area)",82,Government and government enterprises,1687,1811,1931,2035,2120,2191,504.0,29.875521
1,1,32797,"Winston-Salem, NC (Metropolitan Statistical Area)",89,Private goods-producing industries,8346,8821,8138,0,0,7059,-1287.0,-15.420561
2,2,32798,"Winston-Salem, NC (Metropolitan Statistical Area)",90,Private services-providing industries,13657,13737,13576,0,0,15687,2030.0,14.864172
3,3,32877,"Worcester, MA-CT (Metropolitan Statistical Area)",82,Government and government enterprises,4224,4413,4812,5128,5219,5339,1115.0,26.396782
4,4,32884,"Worcester, MA-CT (Metropolitan Statistical Area)",89,Private goods-producing industries,7003,7679,7670,7239,6936,0,-7003.0,-100.000000

In [600]:
metroGDPdatabysector_df2 = metroGDPdatabysector_df1
#Removed Nas
metroGDPdatabysector_df2=metroGDPdatabysector_df2.fillna('0')
metroGDPdatabysector_df2=metroGDPdatabysector_df2.fillna(0)

# metroGDPdatabysector_df2.astype(dtype=int, copy=False,errors='raise')
# metroGDPdatabysector_df1.Percentage_Growth= metroGDPdatabysector_df1.Percentage_Growth.astype(int)
# metroGDPdatabysector_df1.Dollar_Growth = metroGDPdatabysector_df1.Dollar_Growth.astype(int)
metroGDPdatabysector_df2[numericslist].astype(dtype=float, copy=False,errors='raise')
econ_numerics_df = metroGDPdatabysector_df2
x = metroGDPdatabysector_df.convert_objects(convert_numeric=True)
x = x.round(decimals=0)

x = x.convert_objects(convert_numeric=True)
x.fillna('0')
x.fillna(0)
x[['2005','2006','2007','2008','2010','Dollar_Growth','Percentage_Growth']] = x[['2005','2006','2007','2008','2010','Dollar_Growth','Percentage_Growth']].astype(dtype=int, copy=False, errors='ignore')
x.head()
x_desc = x[['2005','2006','2007','2008','2009','2010','Dollar_Growth','Percentage_Growth']].describe()
x_desc
# doesn't work, so

C:\Users\micha\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  # This is added back by InteractiveShellApp.init_path()
C:\Users\micha\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

,2005,2006,2007,2008,2009,2010,Dollar_Growth,Percentage_Growth
count,2.259000e+03,2.259000e+03,2.259000e+03,2.259000e+03,2.259000e+03,2.259000e+03,2259.000000,2131.000000
mean,1.105587e+04,1.146758e+04,1.157212e+04,1.146496e+04,1.105644e+04,1.121058e+04,154.704300,-0.482403
std,1.968968e+05,2.026548e+05,2.062214e+05,2.053466e+05,1.998473e+05,2.046268e+05,10559.289062,NaN
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-181176.000000,-100.000000
25%,9.600000e+01,9.800000e+01,9.900000e+01,1.000000e+02,1.000000e+02,1.000000e+02,-13.000000,-5.000000
50%,1.300000e+02,1.340000e+02,1.250000e+02,1.170000e+02,1.000000e+02,1.100000e+02,4.000000,2.000000
75%,2.475000e+03,2.539500e+03,2.478500e+03,2.467000e+03,2.317500e+03,2.456000e+03,55.000000,9.000000
max,8.779447e+06,9.036366e+06,9.201736e+06,9.182790e+06,8.942675e+06,9.169720e+06,390273.000000,125.000000

In [571]:
# Split into quartiles on 2005 values
    
q = x.copy()

q['Quartiles'] = pd.qcut(q['2005'], 5, labels=list(range(5)))
q

,level_0,index,GeoName,IndustryId,Description,2005,2006,2007,2008,2009,2010,Dollar_Growth,Percentage_Growth,Quartiles
0,0,32790,"Winston-Salem, NC (Metropolitan Statistical Area)",82,Government and government enterprises,1687,1811,1931,2035,2120,2191,504.0,30.0,3
1,1,32797,"Winston-Salem, NC (Metropolitan Statistical Area)",89,Private goods-producing industries,8346,8821,8138,0,0,7059,-1287.0,-15.0,4
2,2,32798,"Winston-Salem, NC (Metropolitan Statistical Area)",90,Private services-providing industries,13657,13737,13576,0,0,15687,2030.0,15.0,4
3,3,32877,"Worcester, MA-CT (Metropolitan Statistical Area)",82,Government and government enterprises,4224,4413,4812,5128,5219,5339,1115.0,26.0,4
4,4,32884,"Worcester, MA-CT (Metropolitan Statistical Area)",89,Private goods-producing industries,7003,7679,7670,7239,6936,0,-7003.0,-100.0,4
5,5,32885,"Worcester, MA-CT (Metropolitan Statistical Area)",90,Private services-providing industries,19520,19806,20045,20584,20406,0,-19520.0,-100.0,4
6,6,32964,"Yakima, WA (Metropolitan Statistical Area)",82,Government and government enterprises,1050,1114,1158,1259,1290,1307,257.0,24.0,3
7,7,32971,"Yakima, WA (Metropolitan Statistical Area)",89,Private goods-producing industries,1997,2037,2255,2263,2156,2361,364.0,18.0,3
8,8,32972,"Yakima, WA (Metropolitan Statistical Area)",90,Private services-providing industries,3250,3393,3609,3910,4143,4457,1207.0,37.0,3
9,9,33051,"York-Hanover, PA (Metropolitan Statistical Area)",82,Government and government enterprises,1474,1570,1693,1791,1897,1982,508.0,34.0,3
10,10,33058,"York-Hanover, PA (Metropolitan Statistical Area)",89,Private goods-producing industries,4972,4888,4761,5018,4841,4868,-104.0,-2.0,4
11,11,33059,"York-Hanover, PA (Metropolitan Statistical Area)",90,Private services-providing industries,8682,8721,9594,10103,9842,9968,1286.0,15.0,4
12,12,33138,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",82,Government and government enterprises,2007,2067,2125,2176,2224,2318,311.0,15.0,3
13,13,33145,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",89,Private goods-producing industries,5897,6440,6180,5429,3591,4448,-1449.0,-25.0,4
14,14,33146,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",90,Private services-providing industries,10576,10997,10901,11005,10583,10737,161.0,2.0,4
15,15,33225,"Yuba City, CA (Metropolitan Statistical Area)",82,Government and government enterprises,1205,1278,1359,1390,1400,1433,228.0,19.0,3
16,16,33232,"Yuba City, CA (Metropolitan Statistical Area)",89,Private goods-producing industries,680,792,873,1049,1177,1096,416.0,61.0,2
17,17,33233,"Yuba City, CA (Metropolitan Statistical Area)",90,Private services-providing industries,2066,2104,2124,2222,2275,2276,210.0,10.0,3
18,18,33312,"Yuma, AZ (Metropolitan Statistical Area)",82,Government and government enterprises,1183,1285,1396,1525,1588,1675,492.0,42.0,3
19,19,33319,"Yuma, AZ (Metropolitan Statistical Area)",89,Private goods-producing industries,1374,1474,1599,1318,1173,1380,6.0,0.0,3
20,20,33320,"Yuma, AZ (Metropolitan Statistical Area)",90,Private services-providing industries,2226,2345,2373,2466,2447,2496,270.0,12.0,3
21,21,33403,United States (Metropolitan Portion),82,Government and government enterprises,96,97,98,99,100,100,4.0,4.0,1
22,22,33410,United States (Metropolitan Portion),89,Private goods-producing industries,105,109,110,106,100,101,-4.0,-4.0,1
23,23,33411,United States (Metropolitan Portion),90,Private services-providing industries,98,101,103,103,100,103,4.0,4.0,1
24,24,33490,"Abilene, TX (Metropolitan Statistical Area)",82,Government and government enterprises,102,101,100,98,100,103,1.0,1.0,1
25,25,33497,"Abilene, TX (Metropolitan Statistical Area)",89,Private goods-producing industries,0,0,0,0,0,0,0.0,NaN,0
26,26,33498,"Abilene, TX (Metropolitan Statistical Area)",90,Private services-providing industries,0,0,0,0,0,0,0.0,NaN,0
27,27,33577,"Akron, OH (Metropolitan Statistical Area)",82,Government and government enterprises,102,99,98,100,100,101,-2.0,-2.0,1
28,28,33584,"Akron, OH (Metropolitan Statistical Area)",89,Private goods-producing industries,119,117,119,112,100,103,-17.0,-14.0,2
29,29,33585,"Akron, OH (Metropolitan Statistical Area)",90,Private services-providing industries,100,100,100,103,100,101,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2229,2229,97439,"Urban Honolulu, HI (Metropolitan Statistical A...",82,Government and government enterprises,11832,12043,11966,12259,12516,12711,879.0,7.0,4
2230,2230,97446,"Urban Honolulu, HI (Metropolitan Statistical A...",89,Private goods-producing industries,4346,4240,4325,4388,4137,3924,-422.0,-10.0,4
2231,2231,97447,"Urban Honolulu, HI (Metropolitan Statistical A...",90,Private services-providing industries,31208,33043,33622,33940,32343,34850,3642.0,12.0,4
2232,2232,97526,"Utica-Rome, NY (Metropolitan Statistical Area)",82,Government and government enterprises,2405,2401,2452,2529,2557,2638,233.0,10.0,3
2233,2233,97533,"Utica-Rome, NY (Metropolitan Statistical Area)",89,Private goods-producing industries,1622,1606,1520,1419,1320,1456,-166.0,-10.0,3
2234,2234,97534,"Utica-Rome, NY (Metropolitan Statistical Area)",90,Private services-providing industries,5455,5703,5692,5693,5802,5741,286.0,5.0,4
2235,2235,97613,"Valdosta, GA (Metropolitan Statistical Area)",82,Government and government enterprises,1109,1069,1039,1083,1145,1197,88.0,8.0,3
2236,2236,97620,"Valdosta, GA (Metropolitan Statistical Area)",89,Private goods-producing industries,951,888,849,802,786,710,-241.0,-25.0,3
2237,2237,97621,"Valdosta, GA (Metropolitan Statistical Area)",90,Private services-providing industries,2247,2360,2527,2383,2386,2494,247.0,11.0,3
2238,2238,97700,"Vallejo-Fairfield, CA (Metropolitan Statistica...",82,Government and government enterprises,3356,3349,3401,3405,3348,3346,-10.0,-0.0,3
2239,2239,97707,"Vallejo-Fairfield, CA (Metropolitan Statistica...",89,Private goods-producing industries,3718,3764,4117,4425,4881,4189,471.0,13.0,4
2240,2240,97708,"Vallejo-Fairfield, CA (Metropolitan Statistica...",90,Private services-providing industries,7767,7542,7199,7536,7418,7554,-213.0,-3.0,4
2241,2241,97787,"Victoria, TX (Metropolitan Statistical Area)",82,Government and government enterprises,413,404,410,415,417,428,15.0,4.0,2
2242,2242,97794,"Victoria, TX (Metropolitan Statistical Area)",89,Private goods-producing industries,1304,1695,1700,0,1444,1650,346.0,27.0,3
2243,2243,97795,"Victoria, TX (Metropolitan Statistical Area)",90,Private services-providing industries,1961,2007,1972,0,1933,2003,42.0,2.0,3
2244,2244,97874,"Vineland-Bridgeton, NJ (Metropolitan Statistic...",82,Government and government enterprises,1233,1207,1227,1253,1255,1221,-12.0,-1.0,3
2245,2245,97881,"Vineland-Bridgeton, NJ (Metropolitan Statistic...",89,Private goods-producing industries,1378,1375,1302,1354,1364,1276,-102.0,-7.0,3
2246,2246,97882,"Vineland-Bridgeton, NJ (Metropolitan Statistic...",90,Private services-providing industries,2813,2886,2781,2831,2806,2728,-85.0,-3.0,3
2247,2247,97961,"Virginia Beach-Norfolk-Newport News, VA-NC (Me...",82,Government and government enterprises,23414,24010,23699,23951,24149,24175,761.0,3.0,4
2248,2248,97968,"Virginia Beach-Norfolk-Newport News, VA-NC (Me...",89,Private goods-producing industries,12552,12531,12334,11437,11921,11602,-950.0,-8.0,4
2249,2249,97969,"Virginia Beach-Norfolk-Newport News, VA-NC (Me...",90,Private services-providing industries,42150,45708,47577,47228,46401,45350,3200.0,8.0,4
2250,2250,98048,"Visalia-Porterville, CA (Metropolitan Statisti...",82,Government and government enterprises,2288,2305,2403,2469,2434,2396,108.0,5.0,3
2251,2251,98055,"Visalia-Porterville, CA (Metropolitan Statisti...",89,Private goods-producing industries,4204,3655,4222,3664,3351,3725,-479.0,-11.0,4
2252,2252,98056,"Visalia-Porterville, CA (Metropolitan Statisti...",90,Private services-providing industries,5264,5820,5679,5805,5439,6249,985.0,19.0,4
2253,2253,98135,"Waco, TX (Metropolitan Statistical Area)",82,Government and government enterprises,1283,1254,1238,1152,1208,1268,-15.0,-1.0,3
2254,2254,98142,"Waco, TX (Metropolitan Statistical Area)",89,Private goods-producing industries,2310,2456,2472,2626,2704,2858,548.0,24.0,3
2255,2255,98143,"Waco, TX (Metropolitan Statistical Area)",90,Private services-providing industries,4802,4808,4836,4938,4826,4961,159.0,3.0,4
2256,2256,98222,"Walla Walla, WA (Metropolitan Statistical Area)",82,Government and government enterprises,428,447,465,512,526,503,75.0,18.0,2
2257,2257,98229,"Walla Walla, WA (Metropolitan Statistical Area)",89,Private goods-producing industries,567,681,670,676,717,720,153.0,27.0,2
2258,2258,98230,"Walla Walla, WA (Metropolitan Statistical Area)",90,Private services-providing industries,1099,1027,1053,1103,1139,1225,126.0,11.0,3

In [ ]:
x1 = []
x2 = []
x3 = []
x4 = []
l=len(x.GeoName)
# mean = 23 #total % gdp growth for the USA
i=1
for i in x.iloc[i:l-1,12]:
    
    idx1 = i
    idx2 = (i+1)
    idx3 = (i+2)                   
    row1,row2, row3=x.iloc[idx1],x.iloc[idx2],x.iloc[idx3]    
    x1.append(row1.Percentage_Growth)                            
    x2.append(row2.Percentage_Growth)                             
    x3.append(row3.Percentage_Growth)
    a = row1.Percentage_Growth 
    b = row2.Percentage_Growth 
    c = row3.Percentage_Growth
    d = a+b+c
    x4.append(d)
    i += 3
print(len(x1),len(x2),len(x3),len(x4))
     
# for row in metroGDPdatabysector_df1['Percentage Growth 05 to 10']:  

#     if row > mean:
      
        
#     elif row < mean:
            
#             worsethanaverage.append(row)
            
#     else:
#             average.append(row)

# print(len(betterthanaverage))

In [603]:
q1 = []
q2 = []
q3 = []
q4 = []
q5 = []
q6 = []
q7 = []
print(q2,q5)

[] []

### Store JSON data into a DataFrame

In [160]:
# json_file = "../Resources/customer_location.json"
# customer_location_df = pd.read_json(json_file)
# customer_location_df.head()

### Clean DataFrame

In [8]:
# new_customer_location_df = customer_location_df[["id", "address", "us_state"]].copy()
# new_customer_location_df.head()

### Connect to local database

In [549]:
connection_string = "root:password@localhost/econ_db"
engine = create_engine(f'mysql://{connection_string}')

### Check for tables

In [10]:
engine.table_names()

['metrogdp']

In [11]:
metroGDPdatabysector_df1.to_sql(name='metrogdp', con=engine, if_exists='append', index=True)

### Use pandas to load json converted DataFrame into database

In [272]:
new_customer_location_df.to_sql(name='customer_location', con=engine, if_exists='append', index=True, index_label='Geo')

NameError: name 'new_customer_location_df' is not defined

### Confirm data has been added by querying the customer_name table
* NOTE: can also check using pgAdmin

In [12]:
pd.read_sql_query('select * from metrogdp', con=engine).head()

,ID,index,GeoName,IndustryId,Description,2005,2006,2007,2008,2009,2010,Growth 05 to 10,Percentage Growth 05 to 10
0,0,78,United States (Metropolitan Portion),82.0,Government and government enterprises,1450899,1521538,1604465,1677648,1727701,1785466,334567.0,23.059290
1,1,85,United States (Metropolitan Portion),89.0,Private goods-producing industries,2294978,2456436,2553858,2531410,2286351,2376763,81785.0,3.563651
2,2,86,United States (Metropolitan Portion),90.0,Private services-providing industries,8044958,8507354,8896629,9020839,8942675,9256252,1211294.0,15.056561
3,3,165,"Abilene, TX (Metropolitan Statistical Area)",82.0,Government and government enterprises,1076,1118,1171,1161,1200,1266,190.0,17.657993
4,4,172,"Abilene, TX (Metropolitan Statistical Area)",89.0,Private goods-producing industries,1180,1333,1499,1832,0,1331,151.0,12.796610

### Confirm data has been added by querying the customer_location table

In [11]:
pd.read_sql_query('select * from customer_location', con=engine).head()

   id                address  us_state
0   1  043 Mockingbird Place   Indiana
1   2       4 Prentice Point   Indiana
2   3      46 Derek Junction     Texas
3   4  11966 Old Shore Place  Missouri
4   5     5 Evergreen Circle  New York